### ISSUE TITLE
Первый пошёл

### ISSUE THREAD

**Issue by D1midr0sh** [QuiXinI/Particles_graphs#2]
Заглавные буквы в переменных? Ты в курсе что так нельзя по пеп8?

**Comment by QuiXinI** [comment]
Ты знал, что такое физические константы? Физика > Информатика => Физ. консты должны быть по правилам физики

**Comment by D1midr0sh** [comment]
Нифига. Ты пишешь на питоне, поэтому должен писать по его правилам. Обозначай как то по другому. 

Отсюда не могу ре-опенить ишью. Дома открою заново.

**Comment by D1midr0sh** [comment]
Да, и это не константы, они тоже с клавиатуры вводятся)
