### ISSUE TITLE
Дебаг? Чё?

### ISSUE THREAD

**Issue by D1midr0sh** [QuiXinI/Particles_graphs#3]
![Screenshot_20230505-135605_GitHub.jpg](https://user-images.githubusercontent.com/93582479/236440363-1ba065d9-21a3-401a-bad6-13d02240bd1e.jpg)

ичо
непонятно что это

**Comment by QuiXinI** [comment]
debug

**Comment by QuiXinI** [comment]
Погоди, у тебя светлая тема? Фу таким быть! Debug щас закрою, с старого релиза остался

**Comment by D1midr0sh** [comment]
чел это приложение для телефона

**Comment by QuiXinI** [comment]
Комитнуто
